/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Planilla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form acceso
     */
    
    public Planilla_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administracion de torneos de una cancha sintetica");
        /*administramos el color de la letra y el tipo de fuente*/
        Font fuente = new Font("Agency FB", Font.PLAIN,40);
        Font fuente1 = new Font("Agency FB", Font.PLAIN,20);
        titulo.setForeground(Color.black);
        titulo.setFont(fuente);
        titulo1.setForeground(Color.black);
        titulo1.setFont(fuente);
        EtiquetaRegistro.setForeground(Color.black);
        EtiquetaRegistro.setFont(fuente1);
        fecha.setForeground(Color.black);
        fecha.setFont(fuente1);
        lugar.setForeground(Color.black);
        lugar.setFont(fuente1);
        hora.setForeground(Color.black);
        hora.setFont(fuente1);
        etiRegistro.setForeground(Color.black);
        etiRegistro.setFont(fuente1);
        etiRegistro1.setForeground(Color.black);
        etiRegistro1.setFont(fuente1);
        arbitro.setForeground(Color.black);
        arbitro.setFont(fuente1);
        nombreEquipo1.setForeground(Color.black);
        nombreEquipo1.setFont(fuente1);
         nombreEquipo2.setForeground(Color.black);
        nombreEquipo2.setFont(fuente1);
         nombreEquipo3.setForeground(Color.black);
        nombreEquipo3.setFont(fuente1);
         nombreEquipo4.setForeground(Color.black);
        nombreEquipo4.setFont(fuente1);
        /*cambiamos el color de los botones*/
        
        Atras.setBackground(Color.lightGray);
        ModificarP.setBackground(Color.lightGray);
        registroAmonestaciones.setBackground(Color.lightGray);
        verResultados.setBackground(Color.lightGray);
        eliminarP1.setBackground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        nombreEquipo4 = new javax.swing.JLabel();
        nombreEquipo3 = new javax.swing.JLabel();
        arbitro = new javax.swing.JLabel();
        nombreEquipo2 = new javax.swing.JLabel();
        nombreEquipo1 = new javax.swing.JLabel();
        verResultados = new javax.swing.JButton();
        etiRegistro1 = new javax.swing.JLabel();
        etiRegistro = new javax.swing.JLabel();
        registroAmonestaciones = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        hora = new javax.swing.JLabel();
        lugar = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        EtiquetaRegistro = new javax.swing.JLabel();
        ModificarP = new javax.swing.JButton();
        Direccion = new javax.swing.JLabel();
        eliminarP1 = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F9 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEquipo4.setText("EQUIPO B :");
        getContentPane().add(nombreEquipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        nombreEquipo3.setText("EQUIPO A :");
        getContentPane().add(nombreEquipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        arbitro.setText("Arbitro :");
        getContentPane().add(arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        nombreEquipo2.setText("FC Lobos ");
        getContentPane().add(nombreEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        nombreEquipo1.setText("Villareal FC ");
        getContentPane().add(nombreEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        verResultados.setText("Ver resultados");
        getContentPane().add(verResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 130, -1));

        etiRegistro1.setText("Click Aqui!");
        getContentPane().add(etiRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        etiRegistro.setText("Para registrar resultados");
        getContentPane().add(etiRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        registroAmonestaciones.setText("Registro resultados ");
        registroAmonestaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAmonestacionesActionPerformed(evt);
            }
        });
        getContentPane().add(registroAmonestaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 140, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 160, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 160, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 160, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 160, 30));

        hora.setText("Hora :");
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        lugar.setText("Lugar :");
        getContentPane().add(lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        fecha.setText("Fecha :");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        EtiquetaRegistro.setText("Registro de planillas ");
        getContentPane().add(EtiquetaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        ModificarP.setText("Modificar");
        getContentPane().add(ModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 90, -1));

        Direccion.setText("Local: Av Primero de mayo, Via la Costa");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        eliminarP1.setText("Eliminar");
        getContentPane().add(eliminarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 90, -1));

        Atras.setText("Atras");
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        titulo1.setText("DON DIEGO ");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 170, 50));

        titulo.setText("ADMINISTRACION DE TORNEOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 350, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/balon1.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 160));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, 310));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 270, 310));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 330));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 330));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 120, 330));

        F9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 120, 310));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 310));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 330, 330));

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 120, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroAmonestacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAmonestacionesActionPerformed
        JOptionPane.showMessageDialog(null, "Si funciona", null, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_registroAmonestacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla_Principal().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel EtiquetaRegistro;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel F9;
    private javax.swing.JButton ModificarP;
    private javax.swing.JLabel arbitro;
    private javax.swing.JButton eliminarP1;
    private javax.swing.JLabel etiRegistro;
    private javax.swing.JLabel etiRegistro1;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lugar;
    private javax.swing.JLabel nombreEquipo1;
    private javax.swing.JLabel nombreEquipo2;
    private javax.swing.JLabel nombreEquipo3;
    private javax.swing.JLabel nombreEquipo4;
    private javax.swing.JButton registroAmonestaciones;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JButton verResultados;
    // End of variables declaration//GEN-END:variables
}
