/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ControladorJPA.ControladorPlanilla;
import Modelo.Planilla;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Planillas extends javax.swing.JFrame {

    /**
     * Creates new form acceso
     */
    DefaultTableModel modelo;
    ControladorPlanilla control = new ControladorPlanilla();

    public Planillas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administracion de torneos de una cancha sintetica");
        /*administramos el color de la letra y el tipo de fuente*/
        Font fuente = new Font("Agency FB", Font.PLAIN, 40);
        Font fuente1 = new Font("Agency FB", Font.PLAIN, 20);
        titulo.setForeground(Color.black);
        titulo.setFont(fuente);
        titulo1.setForeground(Color.black);
        titulo1.setFont(fuente);
        EtiquetaRegistro.setForeground(Color.black);
        EtiquetaRegistro.setFont(fuente1);
        /*cambiamos el color de los botones*/
        buscarEquipo.setBackground(Color.lightGray);
        Atras.setBackground(Color.lightGray);
        RegistrarE.setBackground(Color.lightGray);
        Ver.setBackground(Color.lightGray);

        inicio();
    }

    public void inicio() {
        tablaModelo();
        cargatabla();
    }

    public void tablaModelo() {
        //damos los parametros que se veran reflejados en la tabla
        tablaPlanillas.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaPlanillas.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaPlanillas.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaPlanillas.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaPlanillas.getColumnModel().getColumn(0).setPreferredWidth(80);

        modelo = (DefaultTableModel) tablaPlanillas.getModel();
        modelo.setNumRows(0);
    }

    public void cargatabla() {
        //añadimos a traves de una lista los datos a la tabla
        List<Planilla> lista = control.listarPlanilla();

        for (Planilla actlist : lista) {

            String nombre = String.valueOf(actlist.getNombreEquipo());
            String nombre1 = String.valueOf(actlist.getNombreEquipo1());
            String resultado = String.valueOf(actlist.getResultado());
            String lugar = String.valueOf(actlist.getLugar());
            modelo.addRow(new Object[]{actlist.getId_plani(), nombre, nombre1, resultado, lugar,});
        }
    }

    public void cargaTablaPlanilla(Planilla plani) {
        String nombre = plani.getNombreEquipo();
        String nombre1 = plani.getNombreEquipo1();
        String resultado = plani.getResultado();
        String lugar = plani.getLugar();
        modelo.addRow(new Object[]{plani.getId_plani(), nombre, nombre1, resultado, lugar,});
    }

    public void cargarPlanilla() {
        if (this.tablaPlanillas.isEnabled()) {
            int selectedRow = this.tablaPlanillas.getSelectedRow();
            Long id = Long.parseLong(modelo.getValueAt(selectedRow, 0).toString());
            Planilla plani = control.obtenerPlanilla(id);
            //obteniendo la id para futuas operaciones
            idPlanilla.setText(String.valueOf(plani.getId_plani())); 
            
           
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlanillaPrincipal = new javax.swing.JFrame();
        titulo3 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        etiRegistro1 = new javax.swing.JLabel();
        EtiquetaRegistro1 = new javax.swing.JLabel();
        nombreEquipo3 = new javax.swing.JLabel();
        lbEquipo1 = new javax.swing.JLabel();
        nombreEquipo4 = new javax.swing.JLabel();
        lbEquipo2 = new javax.swing.JLabel();
        etiRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Direccion1 = new javax.swing.JLabel();
        textoArbitro = new javax.swing.JTextField();
        textoLugar = new javax.swing.JTextField();
        textoFecha = new javax.swing.JTextField();
        ModificarP = new javax.swing.JButton();
        eliminarP1 = new javax.swing.JButton();
        registroAmonestaciones = new javax.swing.JButton();
        verResultados = new javax.swing.JButton();
        Atras1 = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        lugar = new javax.swing.JLabel();
        arbitro = new javax.swing.JLabel();
        F12 = new javax.swing.JLabel();
        F13 = new javax.swing.JLabel();
        F14 = new javax.swing.JLabel();
        F15 = new javax.swing.JLabel();
        F16 = new javax.swing.JLabel();
        F17 = new javax.swing.JLabel();
        F11 = new javax.swing.JLabel();
        F18 = new javax.swing.JLabel();
        F19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlanillas = new javax.swing.JTable();
        EtiquetaRegistro = new javax.swing.JLabel();
        Ver = new javax.swing.JButton();
        textoBuscar = new javax.swing.JTextField();
        RegistrarE = new javax.swing.JButton();
        Direccion = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        buscarEquipo = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F9 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        idPlanilla = new javax.swing.JLabel();

        PlanillaPrincipal.getContentPane().setLayout(null);

        titulo3.setText("DON DIEGO ");
        PlanillaPrincipal.getContentPane().add(titulo3);
        titulo3.setBounds(250, 80, 60, 14);

        titulo2.setText("ADMINISTRACION DE TORNEOS");
        PlanillaPrincipal.getContentPane().add(titulo2);
        titulo2.setBounds(120, 40, 156, 14);

        etiRegistro1.setText("Click Aqui!");
        PlanillaPrincipal.getContentPane().add(etiRegistro1);
        etiRegistro1.setBounds(270, 570, 49, 14);

        EtiquetaRegistro1.setText("Registro de planillas ");
        PlanillaPrincipal.getContentPane().add(EtiquetaRegistro1);
        EtiquetaRegistro1.setBounds(30, 140, 98, 14);

        nombreEquipo3.setText("EQUIPO A :");
        PlanillaPrincipal.getContentPane().add(nombreEquipo3);
        nombreEquipo3.setBounds(60, 190, 56, 14);
        PlanillaPrincipal.getContentPane().add(lbEquipo1);
        lbEquipo1.setBounds(60, 250, 0, 0);

        nombreEquipo4.setText("EQUIPO B :");
        PlanillaPrincipal.getContentPane().add(nombreEquipo4);
        nombreEquipo4.setBounds(410, 190, 55, 14);
        PlanillaPrincipal.getContentPane().add(lbEquipo2);
        lbEquipo2.setBounds(420, 250, 0, 0);

        etiRegistro.setText("Para registrar resultados");
        PlanillaPrincipal.getContentPane().add(etiRegistro);
        etiRegistro.setBounds(210, 550, 119, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/balon1.gif"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 140, 220, 160);

        Direccion1.setText("Local: Av Primero de mayo, Via la Costa");
        PlanillaPrincipal.getContentPane().add(Direccion1);
        Direccion1.setBounds(20, 610, 190, 14);
        PlanillaPrincipal.getContentPane().add(textoArbitro);
        textoArbitro.setBounds(200, 340, 180, 20);
        PlanillaPrincipal.getContentPane().add(textoLugar);
        textoLugar.setBounds(200, 380, 180, 20);
        PlanillaPrincipal.getContentPane().add(textoFecha);
        textoFecha.setBounds(200, 420, 180, 20);

        ModificarP.setText("Modificar");
        PlanillaPrincipal.getContentPane().add(ModificarP);
        ModificarP.setBounds(420, 350, 75, 23);

        eliminarP1.setText("Eliminar");
        PlanillaPrincipal.getContentPane().add(eliminarP1);
        eliminarP1.setBounds(420, 400, 69, 23);

        registroAmonestaciones.setText("Registro resultados ");
        registroAmonestaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAmonestacionesActionPerformed(evt);
            }
        });
        PlanillaPrincipal.getContentPane().add(registroAmonestaciones);
        registroAmonestaciones.setBounds(350, 570, 129, 23);

        verResultados.setText("Ver resultados");
        PlanillaPrincipal.getContentPane().add(verResultados);
        verResultados.setBounds(230, 470, 101, 23);

        Atras1.setText("Atras");
        PlanillaPrincipal.getContentPane().add(Atras1);
        Atras1.setBounds(40, 560, 59, 23);

        fecha.setText("Fecha :");
        PlanillaPrincipal.getContentPane().add(fecha);
        fecha.setBounds(150, 420, 36, 14);

        lugar.setText("Lugar :");
        PlanillaPrincipal.getContentPane().add(lugar);
        lugar.setBounds(150, 380, 34, 14);

        arbitro.setText("Arbitro :");
        PlanillaPrincipal.getContentPane().add(arbitro);
        arbitro.setBounds(150, 340, 40, 14);

        F12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F12);
        F12.setBounds(0, 0, 120, 332);

        F13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F13);
        F13.setBounds(120, 0, 120, 332);

        F14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F14);
        F14.setBounds(240, 0, 120, 332);

        F15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F15);
        F15.setBounds(0, 332, 120, 310);

        F16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F16);
        F16.setBounds(120, 330, 120, 310);

        F17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F17);
        F17.setBounds(360, 330, 50, 310);

        F11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F11);
        F11.setBounds(410, 330, 280, 310);

        F18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F18);
        F18.setBounds(360, 0, 332, 332);

        F19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        PlanillaPrincipal.getContentPane().add(F19);
        F19.setBounds(240, 330, 120, 310);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPlanillas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Equipo A", "Equipo B", "Resultado", "Lugar", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPlanillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPlanillasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPlanillas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 370, 220));

        EtiquetaRegistro.setText("Registro de planillas de encuentros");
        getContentPane().add(EtiquetaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Ver.setText("Ver");
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });
        getContentPane().add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 90, -1));

        textoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(textoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, 30));

        RegistrarE.setText("Registrar planilla");
        getContentPane().add(RegistrarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 150, -1));

        Direccion.setText("Local: Av Primero de mayo, Via la Costa");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        Atras.setText("Atras");
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        buscarEquipo.setText("Buscar");
        buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        titulo1.setText("DON DIEGO ");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, 50));

        titulo.setText("ADMINISTRACION DE TORNEOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 350, 50));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, 190));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 270, 190));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 330));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 330));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 120, 330));

        F9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 120, 190));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 190));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 330, 330));

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 120, 190));
        getContentPane().add(idPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBuscarActionPerformed

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        if(idPlanilla.getText().length()>=1){
            Long id = Long.parseLong(idPlanilla.getText());
            Planilla plani = control.obtenerPlanilla(id);
            plani.setId_plani(id);
            //le damos a las etiquetas de la nueva ventana los datos 
            
            dispose();
            PlanillaPrincipal.setVisible(true);
            PlanillaPrincipal.setLocationRelativeTo(null);
            PlanillaPrincipal.setTitle("Administracion de torneos de una cancha sintetica");
            PlanillaPrincipal.setBounds(300, 100, 690, 642);
            
            lbEquipo1.setText(plani.getNombreEquipo());
            lbEquipo2.setText(plani.getNombreEquipo1());
            textoLugar.setText(plani.getLugar());
            textoFecha.setText(String.valueOf(plani.getFecha()));
            textoArbitro.setText(plani.getNombreArbitro());
            
            textoArbitro.setEditable(false);
            textoLugar.setEditable(false);
            textoFecha.setEditable(false);
            
        }
    }//GEN-LAST:event_VerActionPerformed

    private void buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipoActionPerformed
        if (textoBuscar.getText().length() >= 1) {
            Planilla e = null;
            Long numero = Long.parseLong(textoBuscar.getText());
            e = control.obtenerPlanilla(numero);
            if (e != null) {
                tablaModelo();
                cargaTablaPlanilla(e);
            } else {
                JOptionPane.showMessageDialog(null, "No tenemos registro de ese equipo", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene los campos para poder buscar", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarEquipoActionPerformed

    private void registroAmonestacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAmonestacionesActionPerformed
        JOptionPane.showMessageDialog(null, "Si funciona", null, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_registroAmonestacionesActionPerformed

    private void tablaPlanillasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlanillasMouseClicked
        cargarPlanilla();
        
    }//GEN-LAST:event_tablaPlanillasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planillas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Atras1;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel EtiquetaRegistro;
    private javax.swing.JLabel EtiquetaRegistro1;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F11;
    private javax.swing.JLabel F12;
    private javax.swing.JLabel F13;
    private javax.swing.JLabel F14;
    private javax.swing.JLabel F15;
    private javax.swing.JLabel F16;
    private javax.swing.JLabel F17;
    private javax.swing.JLabel F18;
    private javax.swing.JLabel F19;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel F9;
    private javax.swing.JButton ModificarP;
    private javax.swing.JFrame PlanillaPrincipal;
    private javax.swing.JButton RegistrarE;
    private javax.swing.JButton Ver;
    private javax.swing.JLabel arbitro;
    private javax.swing.JButton buscarEquipo;
    private javax.swing.JButton eliminarP1;
    private javax.swing.JLabel etiRegistro;
    private javax.swing.JLabel etiRegistro1;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel idPlanilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEquipo1;
    private javax.swing.JLabel lbEquipo2;
    private javax.swing.JLabel lugar;
    private javax.swing.JLabel nombreEquipo3;
    private javax.swing.JLabel nombreEquipo4;
    private javax.swing.JButton registroAmonestaciones;
    private javax.swing.JTable tablaPlanillas;
    private javax.swing.JTextField textoArbitro;
    private javax.swing.JTextField textoBuscar;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoLugar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JButton verResultados;
    // End of variables declaration//GEN-END:variables
}
