/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author PC
 */
public class Registro_Planilla extends javax.swing.JFrame {

    /**
     * Creates new form acceso
     */
    
    public Registro_Planilla() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administracion de torneos de una cancha sintetica");
        /*administramos el color de la letra y el tipo de fuente*/
        Font fuente = new Font("Agency FB", Font.PLAIN,40);
        Font fuente1 = new Font("Agency FB", Font.PLAIN,20);
        Font fuente2 = new Font("Agency FB", Font.PLAIN,25);
        titulo.setForeground(Color.black);
        titulo.setFont(fuente);
        titulo1.setForeground(Color.black);
        titulo1.setFont(fuente);
        EtiquetaPlanilla.setForeground(Color.black);
        EtiquetaPlanilla.setFont(fuente2);
        nombreEquipoA.setForeground(Color.black);
        nombreEquipoA.setFont(fuente1);
        NombreEquipoB.setForeground(Color.black);
        NombreEquipoB.setFont(fuente1);
        arbitro.setForeground(Color.black);
        arbitro.setFont(fuente1);
        torneo.setForeground(Color.black);
        torneo.setFont(fuente1);
        lugar.setForeground(Color.black);
        lugar.setFont(fuente1);
        fecha.setForeground(Color.black);
        fecha.setFont(fuente1);
        hora.setForeground(Color.black);
        hora.setFont(fuente1);
        
        /*cambiamos el color de los botones*/
        
        Atras.setBackground(Color.lightGray);
        RegistrarP.setBackground(Color.lightGray);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        añoC = new javax.swing.JComboBox();
        mesC = new javax.swing.JComboBox();
        diaC = new javax.swing.JComboBox();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        lugar = new javax.swing.JLabel();
        torneo = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        arbitro = new javax.swing.JLabel();
        NombreEquipoB = new javax.swing.JLabel();
        nombreEquipoA = new javax.swing.JLabel();
        EtiquetaPlanilla = new javax.swing.JLabel();
        RegistrarP = new javax.swing.JButton();
        Direccion = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        F12 = new javax.swing.JLabel();
        F11 = new javax.swing.JLabel();
        F10 = new javax.swing.JLabel();
        F9 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añoC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        añoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoCActionPerformed(evt);
            }
        });
        getContentPane().add(añoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        mesC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesCActionPerformed(evt);
            }
        });
        getContentPane().add(mesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        diaC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        diaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaCActionPerformed(evt);
            }
        });
        getContentPane().add(diaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        fecha.setText("Fecha ");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        hora.setText("Hora :");
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        lugar.setText("Lugar :");
        getContentPane().add(lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        torneo.setText("Torneo :");
        getContentPane().add(torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 210, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 210, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 210, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 260, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 260, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 210, 30));

        arbitro.setText("Arbitro :");
        getContentPane().add(arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        NombreEquipoB.setText("Equipo B: ");
        getContentPane().add(NombreEquipoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        nombreEquipoA.setText("Equipo A: ");
        getContentPane().add(nombreEquipoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        EtiquetaPlanilla.setText("Registro de planillas ");
        getContentPane().add(EtiquetaPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        RegistrarP.setText("Registrar Planilla");
        getContentPane().add(RegistrarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        Direccion.setText("Local: Av Primero de mayo, Via la Costa");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Atras.setText("Atras");
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/balon.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 230, 240));

        titulo1.setText("DON DIEGO ");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 170, 50));

        titulo.setText("ADMINISTRACION DE TORNEOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 350, 50));

        F12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, -1));

        F11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 120, 250));

        F10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 120, 330));

        F9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 120, 240));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 240));

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 120, 250));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, 240));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 290, 240));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 330));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 330));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 120, 330));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 320, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaCActionPerformed

    private void mesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesCActionPerformed

    private void añoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Planilla().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel EtiquetaPlanilla;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F10;
    private javax.swing.JLabel F11;
    private javax.swing.JLabel F12;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel F9;
    private javax.swing.JLabel NombreEquipoB;
    private javax.swing.JButton RegistrarP;
    private javax.swing.JLabel arbitro;
    private javax.swing.JComboBox añoC;
    private javax.swing.JComboBox diaC;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lugar;
    private javax.swing.JComboBox mesC;
    private javax.swing.JLabel nombreEquipoA;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel torneo;
    // End of variables declaration//GEN-END:variables
}
