/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import ControladorJPA.ControladorTorneo;
import Modelo.Torneo;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Torneos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    ControladorTorneo control = new ControladorTorneo();   

    /**
     * Creates new form Torneo
     */
    public Torneos() {
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Administracion de torneos de una cancha sintetica");
        inicio();
    }
    
    public void inicio(){
        tablaModelo();
        cargatabla();
    }
    
    //METODOS PARA MANEJAR LAS TABLAS
     public void cargarTorneo() {
        Torneo torneo = null;
        if (this.tablaTorneo.isEnabled()) {
            int selectedRow = this.tablaTorneo.getSelectedRow();
            
            String nombre = modelo.getValueAt(selectedRow, 0).toString();
            
            //buscamos a ese torneo para traer su id
            torneo = control.obtenerTorneoNombre(nombre);
            Integer num = torneo.getNumeroEquipos();
            control.id_tor = torneo;
            control.numEquipos = num;
            
        }
    }

    public void tablaModelo() {
        //damos los parametros que se veran reflejados en la tabla
        tablaTorneo.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaTorneo.getColumnModel().getColumn(0).setPreferredWidth(40);
        
        modelo = (DefaultTableModel) tablaTorneo.getModel();
        modelo.setNumRows(0);
    }

    public void cargatabla() {
        //añadimos a traves de una lista los datos a la tabla
        List<Torneo> lista = control.listarTorneo();

        for (Torneo actlist : lista) {
            
            String nombre = String.valueOf(actlist.getNombreTorneo());
            String a = String.valueOf(actlist.getNumeroEquipos());   
            modelo.addRow(new Object[]{ nombre, a,});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTorneo = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setText("ADMINISTRACION DE TORNEOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 350, 50));

        titulo1.setText("DON DIEGO ");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 170, 50));

        titu.setText("Los torneos Don Diego :D");
        getContentPane().add(titu, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 118, -1, -1));

        tablaTorneo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Num Equipos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTorneo);
        if (tablaTorneo.getColumnModel().getColumnCount() > 0) {
            tablaTorneo.getColumnModel().getColumn(0).setResizable(false);
            tablaTorneo.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 310, 150));

        btnVer.setText("Ver");
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // llamamos el cargar torneo
        cargarTorneo();
        dispose();
        Equipos v_Equipos = new Equipos();
        v_Equipos.setVisible(true);
    }//GEN-LAST:event_btnVerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torneos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTorneo;
    private javax.swing.JLabel titu;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
